# Generated by Django 3.2.3 on 2021-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=50,
                     unique=True,
                     verbose_name='名称')),
                ('code',
                 models.CharField(
                     max_length=20,
                     unique=True,
                     verbose_name='コード')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'バス路線',
                'verbose_name_plural': 'バス路線',
                                'db_table': 'bus_line',
                                'ordering': ['created_at'],
            },
        ),
    ]
