# Generated by Django 3.2.3 on 2021-05-15 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'バス停',
                'verbose_name_plural': 'バス停',
                'db_table': 'busstop',
                'ordering': ['created_at'],
            },
        ),
    ]
